// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
  name,storage_key,checksum,created_at,updated_at,deleted_at
) VALUES (
  ?, ?, ?,date(),date(),date()
)
RETURNING id, name, storage_key, checksum, created_at, updated_at, deleted_at
`

type CreateFileParams struct {
	Name       string `json:"name"`
	StorageKey string `json:"storage_key"`
	Checksum   string `json:"checksum"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile, arg.Name, arg.StorageKey, arg.Checksum)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, name, storage_key, checksum, created_at, updated_at, deleted_at FROM files
WHERE id = ? LIMIT 1
`

func (q *Queries) GetFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, name, storage_key, checksum, created_at, updated_at, deleted_at FROM files
ORDER BY name
`

func (q *Queries) ListFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StorageKey,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
