// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type File struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	MimeType     string         `json:"mime_type"`
	Size         int64          `json:"size"`
	StorageKey   string         `json:"storage_key"`
	Checksum     string         `json:"checksum"`
	OcrText      string         `json:"ocr_text"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ParentFileID sql.NullString `json:"parent_file_id"`
	IsFolder     bool           `json:"is_folder"`
}

type FileTag struct {
	ID     string         `json:"id"`
	TagID  sql.NullString `json:"tag_id"`
	FileID sql.NullString `json:"file_id"`
}

type RefreshToken struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
	CreatedAt time.Time `json:"created_at"`
}

type Tag struct {
	ID          string         `json:"id"`
	ParentTagID sql.NullString `json:"parent_tag_id"`
	TagName     string         `json:"tag_name"`
	TagType     string         `json:"tag_type"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Thumbnail struct {
	ID              string    `json:"id"`
	FileID          string    `json:"file_id"`
	PageNumber      int32     `json:"page_number"`
	ResolutionLabel string    `json:"resolution_label"`
	Width           int32     `json:"width"`
	Height          int32     `json:"height"`
	StorageKey      string    `json:"storage_key"`
	MimeType        string    `json:"mime_type"`
	CreatedAt       time.Time `json:"created_at"`
}

type User struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
