// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type File struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	MimeType     string         `json:"mime_type"`
	Size         int64          `json:"size"`
	StorageKey   string         `json:"storage_key"`
	Checksum     string         `json:"checksum"`
	OcrText      string         `json:"ocr_text"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	IsFolder     bool           `json:"is_folder"`
	ParentFileID sql.NullString `json:"parent_file_id"`
}

type FileTag struct {
	ID     string         `json:"id"`
	TagID  sql.NullString `json:"tag_id"`
	FileID sql.NullString `json:"file_id"`
}

type Tag struct {
	ID          string         `json:"id"`
	ParentTagID sql.NullString `json:"parent_tag_id"`
	TagName     string         `json:"tag_name"`
	TagType     string         `json:"tag_type"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
