// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: placeholder.sql

package db

import (
	"context"
)

const getHealth = `-- name: GetHealth :one
SELECT 1 AS ok
`

func (q *Queries) GetHealth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getHealth)
	var ok int64
	err := row.Scan(&ok)
	return ok, err
}
