// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagToResource = `-- name: AddTagToResource :exec
INSERT INTO resource_tags (tag_id, resource_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToResourceParams struct {
	TagID      uuid.UUID `json:"tag_id"`
	ResourceID uuid.UUID `json:"resource_id"`
}

func (q *Queries) AddTagToResource(ctx context.Context, arg AddTagToResourceParams) error {
	_, err := q.db.ExecContext(ctx, addTagToResource, arg.TagID, arg.ResourceID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (tag_name)
VALUES ($1)
RETURNING id, parent_tag_id, tag_name, created_at, updated_at
`

func (q *Queries) CreateTag(ctx context.Context, tagName string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, tagName)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.ParentTagID,
		&i.TagName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getResourcesByTagID = `-- name: GetResourcesByTagID :many
SELECT r.id, r.name, r.mime_type, r.size, r.checksum, r.ocr_text, r.is_folder, r.parent_resource_id, r.owner_id, r.created_at, r.updated_at FROM resources r
JOIN resource_tags rt ON r.id = rt.resource_id
WHERE rt.tag_id = $1
ORDER BY r.created_at DESC
`

func (q *Queries) GetResourcesByTagID(ctx context.Context, tagID uuid.UUID) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getResourcesByTagID, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.Size,
			&i.Checksum,
			&i.OcrText,
			&i.IsFolder,
			&i.ParentResourceID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, parent_tag_id, tag_name, created_at, updated_at FROM tags
WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.ParentTagID,
		&i.TagName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, parent_tag_id, tag_name, created_at, updated_at FROM tags
WHERE tag_name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, tagName string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, tagName)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.ParentTagID,
		&i.TagName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagsByResourceID = `-- name: GetTagsByResourceID :many
SELECT t.id, t.parent_tag_id, t.tag_name, t.created_at, t.updated_at FROM tags t
JOIN resource_tags rt ON t.id = rt.tag_id
WHERE rt.resource_id = $1
ORDER BY t.tag_name ASC
`

func (q *Queries) GetTagsByResourceID(ctx context.Context, resourceID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByResourceID, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.ParentTagID,
			&i.TagName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, parent_tag_id, tag_name, created_at, updated_at FROM tags
ORDER BY tag_name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.ParentTagID,
			&i.TagName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromResource = `-- name: RemoveTagFromResource :exec
DELETE FROM resource_tags
WHERE tag_id = $1 AND resource_id = $2
`

type RemoveTagFromResourceParams struct {
	TagID      uuid.UUID `json:"tag_id"`
	ResourceID uuid.UUID `json:"resource_id"`
}

func (q *Queries) RemoveTagFromResource(ctx context.Context, arg RemoveTagFromResourceParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromResource, arg.TagID, arg.ResourceID)
	return err
}
